// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.DAL;

namespace Store.DAL.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20220427033254_db_StoreDbInit")]
    partial class db_StoreDbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Store.Tables.Product", b =>
                {
                    b.Property<int>("Seq_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Product_Code")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delete_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Product_Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Product_Type_Code")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("Update_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Seq_Id", "Product_Code");

                    b.HasIndex("Product_Type_Code");

                    b.ToTable("Products", "Guide");
                });

            modelBuilder.Entity("Store.Tables.ProductCategory", b =>
                {
                    b.Property<int>("Seq_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Product_Category_Code")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Category_Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delete_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("Update_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Seq_Id", "Product_Category_Code");

                    b.ToTable("ProductCategories", "Guide");
                });

            modelBuilder.Entity("Store.Tables.ProductType", b =>
                {
                    b.Property<int>("Seq_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Product_Type_Code")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delete_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Product_Category_Code")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Type_Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Type_Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("Update_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Seq_Id", "Product_Type_Code");

                    b.HasIndex("Product_Category_Code");

                    b.ToTable("ProductTypes", "Guide");
                });

            modelBuilder.Entity("Store.Tables.Product", b =>
                {
                    b.HasOne("Store.Tables.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("Product_Type_Code")
                        .HasPrincipalKey("Product_Type_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Store.Tables.ProductType", b =>
                {
                    b.HasOne("Store.Tables.ProductCategory", "ProductCategory")
                        .WithMany("ProductTypes")
                        .HasForeignKey("Product_Category_Code")
                        .HasPrincipalKey("Product_Category_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Store.Tables.ProductCategory", b =>
                {
                    b.Navigation("ProductTypes");
                });

            modelBuilder.Entity("Store.Tables.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
